"""add translation author

Revision ID: 1ec8d46d3661
Revises: 6a9aa8937c13
Create Date: 2023-05-04 10:33:32.365323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec8d46d3661'
down_revision = '6a9aa8937c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translation_author', sa.String(length=210), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.drop_column('translation_author')

    # ### end Alembic commands ###
