"""Fix spelling error

Revision ID: 20b9c13ea5c2
Revises: 6e807273e355
Create Date: 2022-03-18 01:28:48.255618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b9c13ea5c2'
down_revision = '6e807273e355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translations', sa.Column('link_to_published_translation', sa.Text(), nullable=True))
    op.drop_column('translations', 'link_to_published_transition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translations', sa.Column('link_to_published_transition', sa.TEXT(), nullable=True))
    op.drop_column('translations', 'link_to_published_translation')
    # ### end Alembic commands ###
