"""Add parent object decoration tags

Revision ID: 25bc671fc3f3
Revises: 4d2c27ec9d2d
Create Date: 2022-11-17 10:41:02.242312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25bc671fc3f3'
down_revision = '4d2c27ec9d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_decoration_tags', sa.Column('parent_object_decoration_tag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'object_decoration_tags', 'object_decoration_tags', ['parent_object_decoration_tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'object_decoration_tags', type_='foreignkey')
    op.drop_column('object_decoration_tags', 'parent_object_decoration_tag_id')
    # ### end Alembic commands ###
