"""add further Inscription columns

Revision ID: 268323578818
Revises: f2ebb99a7e79
Create Date: 2022-09-28 13:11:20.493517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268323578818'
down_revision = 'f2ebb99a7e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inscriptions', sa.Column('letter_size_min', sa.Float(), nullable=True))
    op.add_column('inscriptions', sa.Column('letter_size_max', sa.Float(), nullable=True))
    op.add_column('inscriptions', sa.Column('layout_conditioned_by_language', sa.Boolean(), nullable=True))
    op.add_column('inscriptions', sa.Column('date_begin', sa.Integer(), nullable=True))
    op.add_column('inscriptions', sa.Column('date_end', sa.Integer(), nullable=True))
    op.add_column('inscriptions', sa.Column('have_squeeze', sa.Boolean(), nullable=True))
    op.drop_column('inscriptions', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inscriptions', sa.Column('date', sa.TEXT(), nullable=True))
    op.drop_column('inscriptions', 'have_squeeze')
    op.drop_column('inscriptions', 'date_end')
    op.drop_column('inscriptions', 'date_begin')
    op.drop_column('inscriptions', 'layout_conditioned_by_language')
    op.drop_column('inscriptions', 'letter_size_max')
    op.drop_column('inscriptions', 'letter_size_min')
    # ### end Alembic commands ###
