"""Add completeness options to WorkStatus

Revision ID: 26cd268e7592
Revises: 66386fec9fa9
Create Date: 2023-12-07 10:33:20.532166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26cd268e7592'
down_revision = '66386fec9fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_complete', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_incomplete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_status', schema=None) as batch_op:
        batch_op.drop_column('is_incomplete')
        batch_op.drop_column('is_complete')

    # ### end Alembic commands ###
