"""Add full text column

Revision ID: 296bb2729535
Revises: ea96b23fb8b9
Create Date: 2023-07-13 10:33:26.242078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296bb2729535'
down_revision = 'ea96b23fb8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_text_cached', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscriptions', schema=None) as batch_op:
        batch_op.drop_column('full_text_cached')

    # ### end Alembic commands ###
