"""Add main translation+author

Revision ID: 2f9dea96010f
Revises: ff3b6dd0a022
Create Date: 2022-12-08 23:34:27.105521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f9dea96010f'
down_revision = 'ff3b6dd0a022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inscriptions', sa.Column('main_translation', sa.Text(), nullable=True))
    op.add_column('inscriptions', sa.Column('translation_author', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inscriptions', 'translation_author')
    op.drop_column('inscriptions', 'main_translation')
    # ### end Alembic commands ###
