"""Remove layout cond. by lang.

Revision ID: 304b1f8a0f39
Revises: 20dba069c76a
Create Date: 2023-11-02 10:27:22.301008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304b1f8a0f39'
down_revision = '20dba069c76a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscriptions', schema=None) as batch_op:
        batch_op.drop_column('layout_conditioned_by_language')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('layout_conditioned_by_language', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
