"""Fix?

Revision ID: 31c48b583e9a
Revises: 5b9ed241643a
Create Date: 2023-09-07 12:56:33.222570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c48b583e9a'
down_revision = '5b9ed241643a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verse_layouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verse_line_correspondence_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('verse_line_correspondence_verse_layouts_fk', 'verse_line_correspondences', ['verse_line_correspondence_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verse_layouts', schema=None) as batch_op:
        batch_op.drop_constraint('verse_line_correspondence_verse_layouts_fk', type_='foreignkey')
        batch_op.drop_column('verse_line_correspondence_id')

    # ### end Alembic commands ###
