"""Change people to dependent object

Revision ID: 5ed7b21772ed
Revises: c434d55ab405
Create Date: 2023-03-30 10:33:58.608743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed7b21772ed'
down_revision = 'c434d55ab405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscription_people_assoc')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inscription_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('inscription_people_ref', 'inscriptions', ['inscription_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('inscription_people_ref', type_='foreignkey')
        batch_op.drop_column('inscription_id')

    op.create_table('inscription_people_assoc',
    sa.Column('inscription_id', sa.INTEGER(), nullable=True),
    sa.Column('people_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['inscription_id'], ['inscriptions.id'], ),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], )
    )
    # ### end Alembic commands ###
