"""Add import_notice column

Revision ID: 66386fec9fa9
Revises: 304b1f8a0f39
Create Date: 2023-11-23 09:54:01.990496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66386fec9fa9'
down_revision = '304b1f8a0f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_notice', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscriptions', schema=None) as batch_op:
        batch_op.drop_column('import_notice')

    # ### end Alembic commands ###
