"""Add modern_state_id to Places

Revision ID: 6c39d06d66fe
Revises: 7acea1b11368
Create Date: 2023-01-26 10:49:39.649847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c39d06d66fe'
down_revision = '7acea1b11368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modern_state_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('modern_state_on_places_rel', 'modern_states', ['modern_state_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_constraint('modern_state_on_places_rel', type_='foreignkey')
        batch_op.drop_column('modern_state_id')

    # ### end Alembic commands ###
