"""Fix and upgrade people

Revision ID: 6d6b18e97e5d
Revises: a9843ae44402
Create Date: 2021-04-30 15:55:54.701414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6b18e97e5d'
down_revision = 'a9843ae44402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inscription_people_assoc',
    sa.Column('inscription_id', sa.Integer(), nullable=True),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inscription_id'], ['inscriptions.id'], ),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], )
    )
    op.add_column('people', sa.Column('people_age_expression_id', sa.Integer(), nullable=True))
    op.add_column('people', sa.Column('people_age_id', sa.Integer(), nullable=True))
    op.add_column('people', sa.Column('people_age_precision_id', sa.Integer(), nullable=True))
    op.add_column('people', sa.Column('people_legal_status_id', sa.Integer(), nullable=True))
    op.add_column('people', sa.Column('people_origin_id', sa.Integer(), nullable=True))
    op.add_column('people', sa.Column('people_profession_id', sa.Integer(), nullable=True))
    op.add_column('people', sa.Column('people_rank_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'people', 'people_ranks', ['people_rank_id'], ['id'])
    op.create_foreign_key(None, 'people', 'people_age_precision', ['people_age_precision_id'], ['id'])
    op.create_foreign_key(None, 'people', 'people_legal_status', ['people_legal_status_id'], ['id'])
    op.create_foreign_key(None, 'people', 'people_origins', ['people_origin_id'], ['id'])
    op.create_foreign_key(None, 'people', 'people_professions', ['people_profession_id'], ['id'])
    op.create_foreign_key(None, 'people', 'people_age_expressions', ['people_age_expression_id'], ['id'])
    op.create_foreign_key(None, 'people', 'people_ages', ['people_age_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_column('people', 'people_rank_id')
    op.drop_column('people', 'people_profession_id')
    op.drop_column('people', 'people_origin_id')
    op.drop_column('people', 'people_legal_status_id')
    op.drop_column('people', 'people_age_precision_id')
    op.drop_column('people', 'people_age_id')
    op.drop_column('people', 'people_age_expression_id')
    op.drop_table('inscription_people_assoc')
    # ### end Alembic commands ###
