"""add inscription search body cache column

Revision ID: 6e69149a3e62
Revises: 296bb2729535
Create Date: 2023-07-27 10:20:58.830507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e69149a3e62'
down_revision = '296bb2729535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inscription_search_body_cached', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscriptions', schema=None) as batch_op:
        batch_op.drop_column('inscription_search_body_cached')

    # ### end Alembic commands ###
