"""Add dimension columns

Revision ID: 6e807273e355
Revises: 41c46988efec
Create Date: 2021-12-16 23:43:17.853089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e807273e355'
down_revision = '41c46988efec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inscriptions', sa.Column('object_dim_height', sa.Float(), nullable=True))
    op.add_column('inscriptions', sa.Column('object_dim_width', sa.Float(), nullable=True))
    op.add_column('inscriptions', sa.Column('object_dim_depth', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inscriptions', 'object_dim_depth')
    op.drop_column('inscriptions', 'object_dim_width')
    op.drop_column('inscriptions', 'object_dim_height')
    # ### end Alembic commands ###
