"""Add internal comment

Revision ID: 763cac67d8d8
Revises: 26cd268e7592
Create Date: 2023-12-14 10:21:15.914775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763cac67d8d8'
down_revision = '26cd268e7592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internal_comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscriptions', schema=None) as batch_op:
        batch_op.drop_column('internal_comment')

    # ### end Alembic commands ###
