"""Fix foreign key error

Revision ID: 9055d852a11d
Revises: eb90c6dea7b3
Create Date: 2022-12-01 21:24:41.697568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9055d852a11d'
down_revision = 'eb90c6dea7b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inscription_text_layout_tag_assoc', type_='foreignkey')
    op.create_foreign_key(None, 'inscription_text_layout_tag_assoc', 'text_layout_tags', ['text_layout_tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inscription_text_layout_tag_assoc', type_='foreignkey')
    op.create_foreign_key(None, 'inscription_text_layout_tag_assoc', 'verse_types', ['text_layout_tag_id'], ['id'])
    # ### end Alembic commands ###
