"""add places:trismegistos_nr

Revision ID: 9db091944c02
Revises: 1ec8d46d3661
Create Date: 2023-05-11 10:00:42.925218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db091944c02'
down_revision = '1ec8d46d3661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trismegistos_nr', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_column('trismegistos_nr')

    # ### end Alembic commands ###
