"""Add geonames ID

Revision ID: a38d9b920470
Revises: 25bc671fc3f3
Create Date: 2022-12-01 21:19:49.905056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38d9b920470'
down_revision = '25bc671fc3f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('geonames_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'geonames_id')
    # ### end Alembic commands ###
