"""Add LOD columns

Revision ID: a83cbfb74f65
Revises: d30171963a18
Create Date: 2022-03-31 00:15:01.057468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a83cbfb74f65'
down_revision = 'd30171963a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_locations', sa.Column('enum_lod', sa.String(length=150), nullable=True))
    op.add_column('dating_criteria', sa.Column('enum_lod', sa.String(length=150), nullable=True))
    op.add_column('languages', sa.Column('enum_lod', sa.String(length=150), nullable=True))
    op.add_column('object_decoration_tags', sa.Column('enum_lod', sa.String(length=150), nullable=True))
    op.add_column('object_execution_techniques', sa.Column('enum_lod', sa.String(length=150), nullable=True))
    op.add_column('object_materials', sa.Column('enum_lod', sa.String(length=150), nullable=True))
    op.add_column('object_preservation_states', sa.Column('enum_lod', sa.String(length=150), nullable=True))
    op.add_column('object_types', sa.Column('enum_lod', sa.String(length=150), nullable=True))
    op.add_column('people_age_expressions', sa.Column('enum_lod', sa.String(length=150), nullable=True))
    op.add_column('people_age_precision', sa.Column('enum_lod', sa.String(length=150), nullable=True))
    op.add_column('people_ages', sa.Column('enum_lod', sa.String(length=150), nullable=True))
    op.add_column('people_genders', sa.Column('enum_lod', sa.String(length=150), nullable=True))
    op.add_column('people_legal_status', sa.Column('enum_lod', sa.String(length=150), nullable=True))
    op.add_column('people_origins', sa.Column('enum_lod', sa.String(length=150), nullable=True))
    op.add_column('people_professions', sa.Column('enum_lod', sa.String(length=150), nullable=True))
    op.add_column('people_ranks', sa.Column('enum_lod', sa.String(length=150), nullable=True))
    op.add_column('places', sa.Column('enum_lod', sa.String(length=150), nullable=True))
    op.add_column('provinces', sa.Column('enum_lod', sa.String(length=150), nullable=True))
    op.add_column('text_functions', sa.Column('enum_lod', sa.String(length=150), nullable=True))
    op.add_column('verse_timing_types', sa.Column('enum_lod', sa.String(length=150), nullable=True))
    op.add_column('verse_types', sa.Column('enum_lod', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verse_types', 'enum_lod')
    op.drop_column('verse_timing_types', 'enum_lod')
    op.drop_column('text_functions', 'enum_lod')
    op.drop_column('provinces', 'enum_lod')
    op.drop_column('places', 'enum_lod')
    op.drop_column('people_ranks', 'enum_lod')
    op.drop_column('people_professions', 'enum_lod')
    op.drop_column('people_origins', 'enum_lod')
    op.drop_column('people_legal_status', 'enum_lod')
    op.drop_column('people_genders', 'enum_lod')
    op.drop_column('people_ages', 'enum_lod')
    op.drop_column('people_age_precision', 'enum_lod')
    op.drop_column('people_age_expressions', 'enum_lod')
    op.drop_column('object_types', 'enum_lod')
    op.drop_column('object_preservation_states', 'enum_lod')
    op.drop_column('object_materials', 'enum_lod')
    op.drop_column('object_execution_techniques', 'enum_lod')
    op.drop_column('object_decoration_tags', 'enum_lod')
    op.drop_column('languages', 'enum_lod')
    op.drop_column('dating_criteria', 'enum_lod')
    op.drop_column('current_locations', 'enum_lod')
    # ### end Alembic commands ###
