"""Change people reflinks

Revision ID: c434d55ab405
Revises: eba8717adf67
Create Date: 2023-03-30 10:28:42.126804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c434d55ab405'
down_revision = 'eba8717adf67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('r1b1_link', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('trismegistos_link', sa.Text(), nullable=True))
        batch_op.drop_column('reference_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_link', sa.TEXT(), nullable=True))
        batch_op.drop_column('trismegistos_link')
        batch_op.drop_column('r1b1_link')

    # ### end Alembic commands ###
