"""Add further info to places

Revision ID: d30171963a18
Revises: 20b9c13ea5c2
Create Date: 2022-03-24 10:20:09.240129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30171963a18'
down_revision = '20b9c13ea5c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('ancient_name', sa.String(length=90), nullable=True))
    op.add_column('places', sa.Column('modern_name', sa.String(length=90), nullable=True))
    op.add_column('places', sa.Column('coordinates_long', sa.Float(), nullable=True))
    op.add_column('places', sa.Column('coordinates_lat', sa.Float(), nullable=True))
    op.add_column('places', sa.Column('pleiades_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'pleiades_id')
    op.drop_column('places', 'coordinates_lat')
    op.drop_column('places', 'coordinates_long')
    op.drop_column('places', 'modern_name')
    op.drop_column('places', 'ancient_name')
    # ### end Alembic commands ###
