"""Add default work status

Revision ID: d35fb4428085
Revises: 763cac67d8d8
Create Date: 2024-01-10 12:15:07.558352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35fb4428085'
down_revision = '763cac67d8d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_status', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
