"""Use only one epidoc column for text

Revision ID: d646a801a018
Revises: 0670d7402a7a
Create Date: 2022-07-21 09:58:43.824882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd646a801a018'
down_revision = '0670d7402a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inscriptions', sa.Column('text_epidoc_form', sa.Text(), nullable=True))
    op.drop_column('inscriptions', 'text_interpretative_form')
    op.drop_column('inscriptions', 'text_metrics_visualised_form')
    op.drop_column('inscriptions', 'text_diplomatic_form')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inscriptions', sa.Column('text_diplomatic_form', sa.TEXT(), nullable=True))
    op.add_column('inscriptions', sa.Column('text_metrics_visualised_form', sa.TEXT(), nullable=True))
    op.add_column('inscriptions', sa.Column('text_interpretative_form', sa.TEXT(), nullable=True))
    op.drop_column('inscriptions', 'text_epidoc_form')
    # ### end Alembic commands ###
