"""Add name to people ;)

Revision ID: da00907c67cc
Revises: 6d6b18e97e5d
Create Date: 2021-05-17 17:03:06.495199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da00907c67cc'
down_revision = '6d6b18e97e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'name')
    # ### end Alembic commands ###
