"""Add enum_lod to site abbreviations

Revision ID: db9cef379e59
Revises: ee29cfe2c8c1
Create Date: 2026-08-25 13:09:26.422162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db9cef379e59'
down_revision = 'ee29cfe2c8c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_abbreviations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enum_lod', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_abbreviations', schema=None) as batch_op:
        batch_op.drop_column('enum_lod')

    # ### end Alembic commands ###
