"""add subtables for places

Revision ID: f2ebb99a7e79
Revises: d646a801a018
Create Date: 2022-09-28 12:02:58.504425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ebb99a7e79'
down_revision = 'd646a801a018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modern_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('enum_lod', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modern_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('enum_lod', sa.String(length=150), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['modern_states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('places', sa.Column('province_id', sa.Integer(), nullable=True))
    op.add_column('places', sa.Column('modern_region_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'places', 'modern_regions', ['modern_region_id'], ['id'])
    op.create_foreign_key(None, 'places', 'provinces', ['province_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'places', type_='foreignkey')
    op.drop_constraint(None, 'places', type_='foreignkey')
    op.drop_column('places', 'modern_region_id')
    op.drop_column('places', 'province_id')
    op.drop_table('modern_regions')
    op.drop_table('modern_states')
    # ### end Alembic commands ###
